project_name: sealed-secrets-updater
env:
  - CGO_ENABLED=0
builds:
  - binary: sealed-secrets-updater
    id: sealed-secrets-updater
    main: ./cmd/sealed-secrets-updater
    ldflags:
      - -X main.Version={{ .Version }}
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_amd64
      - linux_arm64
      - linux_arm
      - windows_amd64
archives:
  - builds:
      - sealed-secrets-updater
    name_template: "sealed-secrets-updater-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
checksum:
  algorithm: sha256
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^examples:'
release:
  name_template: "{{ .ProjectName }}-v{{ .Version }}"
  header: |
    ## v{{ .Version }} ({{ .Date }})

    New v{{ .Version }} release!
  footer: |
    ## Release Notes

    Please read the [RELEASE_NOTES](https://github.com/juan131/sealed-secrets-updater/blob/main/RELEASE_NOTES.md) which contain among other things important information for who is upgrading from previous releases.

    ## Thanks!
